data.raw.item["fusion-reactor-equipment"].icon = "__more-fusion-reactors__/graphics/item/fusion-reactor-equipment-mk1.png"
data.raw["generator-equipment"]["fusion-reactor-equipment"].sprite.filename = "__more-fusion-reactors__/graphics/equipment/fusion-reactor-equipment-mk1.png"

data:extend(
{
	{
	  type = "item",
	  name = "fusion-reactor-equipment-mk2",
	  icon = "__more-fusion-reactors__/graphics/item/fusion-reactor-equipment-mk2.png",
	  icon_size = 64, icon_mipmaps = 4,
	  placed_as_equipment_result = "fusion-reactor-equipment-mk2",
	  subgroup = "equipment",
	  order = "aab[fusion-reactor]",
	  default_request_amount = 1,
	  stack_size = 25,
	},
	{
	  type = "item",
	  name = "fusion-reactor-equipment-mk3",
	  icon = "__more-fusion-reactors__/graphics/item/fusion-reactor-equipment-mk3.png",
	  icon_size = 64, icon_mipmaps = 4,
	  placed_as_equipment_result = "fusion-reactor-equipment-mk3",
	  subgroup = "equipment",
	  order = "aac[fusion-reactor]",
	  default_request_amount = 1,
	  stack_size = 30,
	},
	{
	  type = "item",
	  name = "fusion-reactor-equipment-mk4",
	  icon = "__more-fusion-reactors__/graphics/item/fusion-reactor-equipment-mk4.png",
	  icon_size = 64, icon_mipmaps = 4,
	  placed_as_equipment_result = "fusion-reactor-equipment-mk4",
	  subgroup = "equipment",
	  order = "aad[fusion-reactor]",
	  default_request_amount = 1,
	  stack_size = 40,
	},
	{
	  type = "item",
	  name = "fusion-reactor-equipment-mk5",
	  icon = "__more-fusion-reactors__/graphics/item/fusion-reactor-equipment-mk5.png",
	  icon_size = 64, icon_mipmaps = 4,
	  placed_as_equipment_result = "fusion-reactor-equipment-mk5",
	  subgroup = "equipment",
	  order = "aae[fusion-reactor]",
	  default_request_amount = 1,
	  stack_size = 45,
	},
	{
	  type = "item",
	  name = "fusion-reactor-equipment-mk6",
	  icon = "__more-fusion-reactors__/graphics/item/fusion-reactor-equipment-mk6.png",
	  icon_size = 64, icon_mipmaps = 4,
	  placed_as_equipment_result = "fusion-reactor-equipment-mk6",
	  subgroup = "equipment",
	  order = "aae[fusion-reactor]",
	  default_request_amount = 1,
	  stack_size = 50,
	},
})