local speaker = data.raw["programmable-speaker"]["programmable-speaker"]
speaker.instruments[#speaker.instruments+1] = {
    name = "Command_and_Conquer_RedAlert_sounds",
    notes = {
        {name = "Building placement", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/building_placement.wav"}},
        {name = "Building placed", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/building_placed.wav"}},		
        {name = "Building half destroyed", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/building_half_destroyed.wav"}},
        {name = "Building destroyed", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/building_destroyed.wav"}},
        {name = "Chronosphere", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/chronosphere.wav"}},
        {name = "Flame-Turret up", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/flame_turret_up.wav"}},
        {name = "Flame-Turret down", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/flame_turret_down.wav"}},
        {name = "Medic heal", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/medic_heal.wav"}},
        {name = "iron_curtain", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/iron_curtain.wav"}},
        {name = "Mine placed", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/mine_placed.wav"}},
        {name = "Paratroops", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/paratroops.wav"}},
        {name = "Power up", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/power_up.wav"}},
        {name = "Power down", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/power_down.wav"}},
        {name = "Radar power", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/radar_power.wav"}},
        {name = "Selling", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/selling.wav"}},
        {name = "Sonar pulse", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/sonar_pulse.wav"}},
        {name = "Sub uncloaking", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/sub_uncloaking.wav"}},
        {name = "Tesla charge", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/tesla_charge.wav"}},
        {name = "Tesla shot", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/sounds/tesla_shot.wav"}},
    }
}

speaker.instruments[#speaker.instruments+1] = {
    name = "Command_and_Conquer_RedAlert_notes",
    notes = {
        {name = "alarm", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/alarm.wav"}},
        {name = "appear1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/appear1.wav"}},
        {name = "beepy6", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/beepy6.wav"}},
        {name = "bleep_1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/bleep_1.wav"}},
        {name = "bleep_2", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/bleep_2.wav"}},
        {name = "briefing", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/briefing.wav"}},
        {name = "clock1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/clock1.wav"}},
        {name = "country1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/country1.wav"}},
        {name = "country4", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/country4.wav"}},
        {name = "credit_in", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/credit_in.wav"}},
        {name = "credit_out", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/credit_out.wav"}},
        {name = "drill7", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/drill7.wav"}},
        {name = "keystroke", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/keystroke.wav"}},
        {name = "map_sound_2", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/map_sound_2.wav"}},
        {name = "map_sound_4", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/map_sound_4.wav"}},
        {name = "map_sound_5", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/map_sound_5.wav"}},
        {name = "map_sound_7", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/map_sound_7.wav"}},
        {name = "map_sound_8", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/map_sound_8.wav"}},
        {name = "map_sound_9", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/map_sound_9.wav"}},
        {name = "mapwipe2", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/mapwipe2.wav"}},
        {name = "mapwipe5", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/mapwipe5.wav"}},
        {name = "radar_alert", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/radar_alert.wav"}},
        {name = "scold1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/scold1.wav"}},
        {name = "sfx4", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/sfx4.wav"}},
        {name = "sparks1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/sparks1.wav"}},
        {name = "texty1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/texty1.wav"}},
        {name = "toney4", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/toney4.wav"}},
        {name = "toney5", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/toney5.wav"}},
        {name = "toney6", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/toney6.wav"}},
        {name = "toney7", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/toney7.wav"}},
        {name = "toney10", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/alarm&notes/toney10.wav"}},
    }
}

speaker.instruments[#speaker.instruments+1] = {
    name = "Command_and_Conquer_RedAlert_voices",
    notes = {
        {name = "aarrive1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/aarrive1.wav"}},
        {name = "baseatk1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/baseatk1.wav"}},
        {name = "bct1", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/bct1.wav"}},
        {name = "building in progress", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/building in progress.wav"}},
        {name = "building infiltrated", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/building infiltrated.wav"}},
        {name = "building", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/building.wav"}},
        {name = "cancelled", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/cancelled.wav"}},
        {name = "command centre under attack", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/command centre under attack.wav"}},
        {name = "construction complete", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/construction complete.wav"}},
        {name = "Dog wouf", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/dog_wouf.wav"}},
        {name = "Dog angry", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/dog_angry.wav"}},
        {name = "Dog angry 2", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/dog_angry_2.wav"}},
        {name = "enemy approaching", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/enemy approaching.wav"}},
        {name = "gps sattelite launched", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/gps sattelite launched.wav"}},
        {name = "insufficient power", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/insufficient power.wav"}},
        {name = "low power", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/low power.wav"}},
        {name = "mission accomplished", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/mission accomplished.wav"}},
        {name = "your mission is a failure", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/your mission is a failure.wav"}},
        {name = "mission timer initialised", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/mission timer initialised.wav"}},
        {name = "repairing", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/repairing.wav"}},
        {name = "select target", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/select target.wav"}},
        {name = "silos needed", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/silos needed.wav"}},
        {name = "soviet empire has fallen", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/soviet empire has fallen.wav"}},
        {name = "structure destroyed", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/structure destroyed.wav"}},
        {name = "Tanya laugh", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/tanya_laugh.wav"}},
        {name = "timer started", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/timer started.wav"}},
        {name = "timer stopped", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/timer stopped.wav"}},
        {name = "unable to build more", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/unable to build more.wav"}},
        {name = "unit lost", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/unit lost.wav"}},
        {name = "unit ready", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/voices/unit ready.wav"}},

    }
}

--speaker.instruments[#speaker.instruments+1] = {	
--	name = "Command_and_Conquer_RedAlert_war",
--    notes = {
--        {name = "Air 2 Air missile", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/air2air_missile.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--        {name = "", sound = {filename = "__Command_and_Conquer_RedAlert_Sounds__/sound_files/shots&explosions/.wav"}},
--    }
--}