require("prototypes.item")
require("prototypes.entity")
require("prototypes.recipe")
require("prototypes.technology")
require("prototypes.module")
require("prototypes.item-groups")
require("prototypes.recipe-category")