data:extend({
    {
        type = "int-setting",
        name = "induction-charging-tickrate",
        setting_type = "runtime-global",
        default_value = 15,
        maximum_value = 300,
        minimum_value = 1,
        order = "induction-charging-aa[tickrate]",
    },
    {
        type = "int-setting",
        name = "induction-charging-gui-tickrate",
        setting_type = "runtime-global",
        default_value = 4,
        maximum_value = 100,
        minimum_value = 1,
        order = "induction-charging-bb[gui-tickrate]",
    },
    {
        type = "double-setting",
        name = "induction-charging-score-base",
        setting_type = "runtime-global",
        default_value = 0.50,
        maximum_value = 1,
        minimum_value = 0,
        order = "induction-charging-cc[score-base]",
    },
    {
        type = "double-setting",
        name = "induction-charging-score-neighbour",
        setting_type = "runtime-global",
        default_value = 0.05,
        maximum_value = 1,
        minimum_value = 0,
        order = "induction-charging-dd[score-neighbour]",
    },
    {
        type = "double-setting",
        name = "induction-charging-score-neighbour-without-whitespace",
        setting_type = "runtime-global",
        default_value = 0.12,
        maximum_value = 1,
        minimum_value = 0,
        order = "induction-charging-ee[score-neighbour-without-whitespace]",
    },
})