local data_util = require("data_util")
data:extend({
  {
    type = "item",
    name = data_util.mod_prefix .. "space-capsule",
    place_result = data_util.mod_prefix .. "space-capsule-_-vehicle",
    icon = "__space-exploration-graphics__/graphics/icons/space-capsule.png",
    icon_size = 32,
    order = "d",
    stack_size = 1,
    subgroup = "rocket-logistics",
  },
  {
    type = "item",
    name = data_util.mod_prefix .. "cargo-rocket-section",
    icon = "__space-exploration-graphics__/graphics/icons/cargo-rocket-section.png",
    icon_size = 32,
    order = "q[rocket-part]",
    stack_size = 1,
    subgroup = "rocket-intermediate-product",
  },
  {
    type = "item",
    name = data_util.mod_prefix .. "cargo-rocket-section-packed",
    icon = "__space-exploration-graphics__/graphics/icons/cargo-rocket-section-stacked.png",
    icon_size = 32,
    order = "q[rocket-part]-b",
    stack_size = 1,
    subgroup = "rocket-intermediate-product",
  },
  {
    type = "item",
    name = data_util.mod_prefix .. "cargo-rocket-cargo-pod",
    place_result = data_util.mod_prefix .. "cargo-rocket-cargo-pod",
    icon = "__space-exploration-graphics__/graphics/icons/cargo-pod.png",
    icon_size = 32,
    order = "q[rocket-part]",
    stack_size = 10,
    subgroup = "rocket-intermediate-product",
  },
  {
    type = "item",
    name = data_util.mod_prefix .. "cargo-rocket-fuel-tank",
    icon = "__space-exploration-graphics__/graphics/icons/rocket-fuel-tank.png",
    icon_size = 32,
    order = "q[rocket-part]",
    stack_size = 10,
    subgroup = "rocket-intermediate-product",
  },
})
