data:extend({
    {
        type = "bool-setting",
        name = "AR-use-items-from-bioindustries",
        setting_type = "startup",
        default_value = true,
        order  = "a",
    },
    {
        type = "bool-setting",
        name = "AR-use-items-from-woodgasification",
        setting_type = "startup",
        default_value = true,
        order  = "b",
    },
    {
        type = "string-setting",
        name = "AR-research-cost",
        setting_type = "startup",
        default_value = "level-1",
        allowed_values = {"level-0", "level-1", "level-2"},
        order  = "c",
    },	
    {
        type = "int-setting",
        name = "AR-asphalt-stack-size",
        setting_type = "startup",
        default_value = 100,
        minimum_value = 10,
        maximum_value = 1000,
        order = "d",
    },
    {
        type = "string-setting",
        name = "AR-item-group",
        setting_type = "startup",
        default_value = "logistics",
        allowed_values = {"logistics", "dectorio", "asphalt"},
        order = "e",    
    },
	{
        type = "bool-setting",
        name = "AR-enable-basic-marking-tiles",
        setting_type = "startup",
        default_value = true,
        order  = "f1",
    },	
	{
        type = "bool-setting",
        name = "AR-enable-colored-hazard-marking",
        setting_type = "startup",
        default_value = true,
        order  = "f2",
    },		
	{
        type = "bool-setting",
        name = "AR-enable-white-single-lines",
        setting_type = "startup",
        default_value = true,
        order  = "f3",
    },
	{
        type = "bool-setting",
        name = "AR-enable-white-double-lines",
        setting_type = "startup",
        default_value = true,
        order  = "f4",
    },
	{
        type = "bool-setting",
        name = "AR-enable-yellow-single-lines",
        setting_type = "startup",
        default_value = true,
        order  = "f5",
    },	
	{
        type = "bool-setting",
        name = "AR-enable-yellow-double-lines",
        setting_type = "startup",
        default_value = true,
        order  = "f6",
    }
})

