-- data:extend(
-- {
    -- {
    -- type = "technology",
    -- name = "nilaus",
    -- icon = "__angelsaddons-oresilos__/graphics/technology/silo-tech.png",
	-- icon_size = 128,
	-- prerequisites =
    -- {
	-- "steel-processing",
    -- },
    -- effects =
    -- {
	  -- {
        -- type = "unlock-recipe",
        -- recipe = "silo"
      -- },
    -- },
    -- unit =
    -- {
      -- count = 30,
      -- ingredients = {
	  -- {"science-pack-1", 1},
	  -- },
      -- time = 15
    -- },
    -- order = "c-a"
    -- },
-- }
-- )