data:extend(
  {
    {
      type = "artillery-wagon",
      name = "schwerer-gustav",
      icon = "__base__/graphics/icons/artillery-wagon.png",
      icon_size = 32,
      flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
      inventory_size = 1,
      ammo_stack_limit = 100,
      minable = {mining_time = 1, result = "artillery-wagon"},
      mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
      max_health = 600,
      corpse = "medium-remnants",
      dying_explosion = "medium-explosion",
      collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
      selection_box = {{-1, -2.703125}, {1, 3.296875}},
      vertical_selection_shift = -0.796875,
      weight = 4000,
      max_speed = 1.5,
      braking_force = 3,
      friction_force = 0.50,
      air_resistance = 0.015,
      connection_distance = 3,
      joint_distance = 4,
      energy_per_hit_point = 2,
      gun = "artillery-wagon-cannon",
      turret_rotation_speed = 0.001,
      turn_after_shooting_cooldown = 60,
      cannon_parking_frame_count = 8,
      cannon_parking_speed = 0.25,
      manual_range_modifier = 2.5,
      resistances = {
        {
          type = "fire",
          decrease = 15,
          percent = 50
        },
        {
          type = "physical",
          decrease = 15,
          percent = 30
        },
        {
          type = "impact",
          decrease = 50,
          percent = 50
        },
        {
          type = "explosion",
          decrease = 15,
          percent = 30
        },
        {
          type = "acid",
          decrease = 10,
          percent = 20
        }
      },
      back_light = rolling_stock_back_light(),
      stand_by_light = rolling_stock_stand_by_light(),
      color = {r = 0.43, g = 0.23, b = 0, a = 0.5},
      pictures = {
        layers = {
          {
            priority = "very-low",
            width = 238,
            height = 206,
            direction_count = 256,
            allow_low_quality_rotation = true,
            line_length = 4,
            lines_per_file = 4,
            shift = util.by_pixel(0, -27 * 4),
            slice = 4,
            scale = 4,
            filenames = {
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-1.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-2.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-3.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-4.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-5.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-6.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-7.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-8.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-9.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-10.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-11.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-12.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-13.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-14.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-15.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-16.png"
            },
            hr_version = {
              priority = "very-low",
              width = 476,
              height = 410,
              direction_count = 256,
              allow_low_quality_rotation = true,
              line_length = 4,
              lines_per_file = 4,
              shift = util.by_pixel(0.5 * 2, -27.5 * 2),
              scale = 2,
              slice = 4,
              filenames = {
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-1.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-2.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-3.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-4.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-5.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-6.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-7.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-8.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-9.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-10.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-11.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-12.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-13.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-14.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-15.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-16.png"
              }
            }
          },
          {
            priority = "very-low",
            slice = 4,
            scale = 4,
            width = 300,
            height = 240,
            direction_count = 256,
            allow_low_quality_rotation = true,
            line_length = 4,
            lines_per_file = 4,
            shift = util.by_pixel(3 * 47, 6 * 4),
            draw_as_shadow = true,
            filenames = {
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-1.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-2.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-3.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-4.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-5.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-6.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-7.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-8.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-9.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-10.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-11.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-12.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-13.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-14.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-15.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-16.png"
            },
            hr_version = {
              priority = "very-low",
              slice = 4,
              width = 598,
              height = 480,
              direction_count = 256,
              allow_low_quality_rotation = true,
              line_length = 4,
              lines_per_file = 4,
              shift = util.by_pixel(36.5 * 2, 6.5 * 2),
              --v
              scale = 2,
              draw_as_shadow = true,
              filenames = {
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-1.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-2.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-3.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-4.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-5.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-6.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-7.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-8.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-9.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-10.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-11.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-12.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-13.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-14.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-15.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-16.png"
              }
            }
          }
        }
      },
      cannon_barrel_pictures = {
        layers = {
          {
            priority = "very-low",
            width = 266,
            height = 192,
            direction_count = 256,
            line_length = 4,
            lines_per_file = 4,
            shift = util.by_pixel(0, -56 * 4),
            scale = 4,
            filenames = {
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-1.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-2.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-3.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-4.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-5.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-6.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-7.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-8.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-9.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-10.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-11.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-12.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-13.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-14.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-15.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-16.png"
            },
            hr_version = {
              priority = "very-low",
              width = 530,
              height = 384,
              direction_count = 256,
              line_length = 4,
              lines_per_file = 4,
              shift = util.by_pixel(0, -56 * 2),
              scale = 2,
              filenames = {
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-1.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-2.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-3.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-4.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-5.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-6.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-7.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-8.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-9.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-10.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-11.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-12.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-13.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-14.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-15.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-16.png"
              }
            }
          },
          {
            priority = "very-low",
            width = 454,
            height = 314,
            direction_count = 256,
            line_length = 4,
            lines_per_file = 4,
            shift = util.by_pixel(-3 + 58 * 4, 8 + 46 * 4),
            draw_as_shadow = true,
            scale = 4,
            filenames = {
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-1.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-2.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-3.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-4.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-5.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-6.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-7.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-8.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-9.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-10.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-11.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-12.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-13.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-14.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-15.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-16.png"
            },
            hr_version = {
              priority = "very-low",
              width = 906,
              height = 626,
              direction_count = 256,
              line_length = 4,
              lines_per_file = 4,
              shift = util.by_pixel(-3.5 + 58 * 2, 7.5 + 46 * 2),
              scale = 2,
              draw_as_shadow = true,
              filenames = {
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-1.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-2.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-3.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-4.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-5.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-6.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-7.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-8.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-9.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-10.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-11.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-12.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-13.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-14.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-15.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-16.png"
              }
            }
          }
        }
      },
      cannon_base_pictures = {
        layers = {
          {
            priority = "very-low",
            width = 180,
            height = 136,
            direction_count = 256,
            line_length = 4,
            lines_per_file = 4,
            shift = util.by_pixel(0, -40 * 10),
            scale = 4,
            filenames = {
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-1.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-2.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-3.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-4.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-5.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-6.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-7.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-8.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-9.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-10.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-11.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-12.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-13.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-14.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-15.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-16.png"
            },
            hr_version = {
              priority = "very-low",
              width = 358,
              height = 270,
              direction_count = 256,
              line_length = 4,
              lines_per_file = 4,
              shift = util.by_pixel(0, -40.5 * 12),
              scale = 2,
              filenames = {
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-1.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-2.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-3.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-4.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-5.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-6.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-7.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-8.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-9.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-10.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-11.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-12.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-13.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-14.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-15.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-16.png"
              }
            }
          },
          {
            priority = "very-low",
            width = 238,
            height = 170,
            direction_count = 256,
            line_length = 4,
            lines_per_file = 4,
            shift = util.by_pixel(54 + 58 * 4, -1 + 46 * 4),
            draw_as_shadow = true,
            scale = 4,
            filenames = {
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-1.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-2.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-3.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-4.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-5.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-6.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-7.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-8.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-9.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-10.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-11.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-12.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-13.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-14.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-15.png",
              "__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-16.png"
            },
            hr_version = {
              priority = "very-low",
              width = 476,
              height = 340,
              direction_count = 256,
              line_length = 4,
              lines_per_file = 4,
              shift = util.by_pixel(54.5 + 58 * 2, -1 + 46 * 2),
              scale = 2,
              draw_as_shadow = true,
              filenames = {
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-1.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-2.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-3.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-4.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-5.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-6.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-7.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-8.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-9.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-10.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-11.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-12.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-13.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-14.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-15.png",
                "__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-16.png"
              }
            }
          }
        }
      },
      cannon_base_shiftings = {
        util.by_pixel(0.0, 19.5),
        util.by_pixel(-1.5, 19.0),
        util.by_pixel(-3.5, 19.0),
        util.by_pixel(-5.5, 18.5),
        util.by_pixel(-7.5, 18.5),
        util.by_pixel(-9.0, 18.0),
        util.by_pixel(-11.0, 17.5),
        util.by_pixel(-13.0, 17.5),
        util.by_pixel(-15.0, 17.0),
        util.by_pixel(-16.5, 16.5),
        util.by_pixel(-18.5, 16.0),
        util.by_pixel(-20.5, 15.5),
        util.by_pixel(-22.0, 15.0),
        util.by_pixel(-24.0, 14.5),
        util.by_pixel(-25.5, 14.0),
        util.by_pixel(-27.5, 13.0),
        util.by_pixel(-29.0, 12.5),
        util.by_pixel(-30.5, 12.0),
        util.by_pixel(-32.0, 11.0),
        util.by_pixel(-34.0, 10.5),
        util.by_pixel(-35.5, 9.5),
        util.by_pixel(-37.0, 9.0),
        util.by_pixel(-38.5, 8.0),
        util.by_pixel(-40.0, 7.5),
        util.by_pixel(-41.5, 6.5),
        util.by_pixel(-42.5, 5.5),
        util.by_pixel(-44.0, 4.5),
        util.by_pixel(-45.5, 4.0),
        util.by_pixel(-46.5, 3.0),
        util.by_pixel(-48.0, 2.0),
        util.by_pixel(-49.0, 1.0),
        util.by_pixel(-50.5, 0.0),
        util.by_pixel(-51.5, -0.5),
        util.by_pixel(-52.5, -1.5),
        util.by_pixel(-53.5, -2.5),
        util.by_pixel(-54.5, -3.5),
        util.by_pixel(-55.5, -5.0),
        util.by_pixel(-56.5, -6.0),
        util.by_pixel(-57.5, -7.0),
        util.by_pixel(-58.0, -8.0),
        util.by_pixel(-59.0, -9.0),
        util.by_pixel(-60.0, -10.5),
        util.by_pixel(-60.5, -11.5),
        util.by_pixel(-61.0, -12.5),
        util.by_pixel(-62.0, -13.5),
        util.by_pixel(-62.5, -15.0),
        util.by_pixel(-63.0, -16.0),
        util.by_pixel(-63.5, -17.0),
        util.by_pixel(-64.0, -18.5),
        util.by_pixel(-64.5, -19.5),
        util.by_pixel(-65.0, -21.0),
        util.by_pixel(-65.0, -22.0),
        util.by_pixel(-65.5, -23.0),
        util.by_pixel(-65.5, -24.5),
        util.by_pixel(-66.0, -25.5),
        util.by_pixel(-66.0, -26.5),
        util.by_pixel(-66.0, -28.0),
        util.by_pixel(-66.5, -29.0),
        util.by_pixel(-66.5, -30.0),
        util.by_pixel(-66.5, -31.5),
        util.by_pixel(-66.5, -32.5),
        util.by_pixel(-66.0, -34.0),
        util.by_pixel(-66.0, -35.0),
        util.by_pixel(-66.0, -36.0),
        util.by_pixel(-65.5, -37.0),
        util.by_pixel(-66.0, -38.5),
        util.by_pixel(-66.0, -39.5),
        util.by_pixel(-66.5, -40.5),
        util.by_pixel(-66.5, -42.0),
        util.by_pixel(-66.5, -43.0),
        util.by_pixel(-66.5, -44.0),
        util.by_pixel(-66.5, -45.5),
        util.by_pixel(-66.5, -46.5),
        util.by_pixel(-66.5, -48.0),
        util.by_pixel(-66.0, -49.0),
        util.by_pixel(-66.0, -50.0),
        util.by_pixel(-65.5, -51.5),
        util.by_pixel(-65.5, -52.5),
        util.by_pixel(-65.0, -53.5),
        util.by_pixel(-64.5, -55.0),
        util.by_pixel(-64.5, -56.0),
        util.by_pixel(-64.0, -57.5),
        util.by_pixel(-63.5, -58.5),
        util.by_pixel(-63.0, -59.5),
        util.by_pixel(-62.5, -61.0),
        util.by_pixel(-61.5, -62.0),
        util.by_pixel(-61.0, -63.0),
        util.by_pixel(-60.5, -64.0),
        util.by_pixel(-59.5, -65.5),
        util.by_pixel(-59.0, -66.5),
        util.by_pixel(-58.0, -67.5),
        util.by_pixel(-57.0, -68.5),
        util.by_pixel(-56.0, -70.0),
        util.by_pixel(-55.0, -71.0),
        util.by_pixel(-54.0, -72.0),
        util.by_pixel(-53.0, -73.0),
        util.by_pixel(-52.0, -74.0),
        util.by_pixel(-51.0, -75.0),
        util.by_pixel(-50.0, -76.0),
        util.by_pixel(-48.5, -77.0),
        util.by_pixel(-47.5, -78.0),
        util.by_pixel(-46.0, -79.0),
        util.by_pixel(-45.0, -80.0),
        util.by_pixel(-43.5, -81.0),
        util.by_pixel(-42.0, -81.5),
        util.by_pixel(-40.5, -82.5),
        util.by_pixel(-39.5, -83.5),
        util.by_pixel(-38.0, -84.0),
        util.by_pixel(-36.5, -85.0),
        util.by_pixel(-34.5, -85.5),
        util.by_pixel(-33.0, -86.5),
        util.by_pixel(-31.5, -87.0),
        util.by_pixel(-30.0, -88.0),
        util.by_pixel(-28.5, -88.5),
        util.by_pixel(-26.5, -89.0),
        util.by_pixel(-25.0, -90.0),
        util.by_pixel(-23.0, -90.5),
        util.by_pixel(-21.5, -91.0),
        util.by_pixel(-19.5, -91.5),
        util.by_pixel(-17.5, -92.0),
        util.by_pixel(-16.0, -92.5),
        util.by_pixel(-14.0, -93.0),
        util.by_pixel(-12.0, -93.0),
        util.by_pixel(-10.5, -93.5),
        util.by_pixel(-8.5, -94.0),
        util.by_pixel(-6.5, -94.0),
        util.by_pixel(-4.5, -94.5),
        util.by_pixel(-2.5, -94.5),
        util.by_pixel(-0.5, -95.0),
        util.by_pixel(1.0, -95.0),
        util.by_pixel(3.0, -94.5),
        util.by_pixel(5.0, -94.5),
        util.by_pixel(7.0, -94.0),
        util.by_pixel(8.5, -94.0),
        util.by_pixel(10.5, -93.5),
        util.by_pixel(12.5, -93.0),
        util.by_pixel(14.5, -92.5),
        util.by_pixel(16.5, -92.5),
        util.by_pixel(18.0, -92.0),
        util.by_pixel(20.0, -91.5),
        util.by_pixel(21.5, -91.0),
        util.by_pixel(23.5, -90.5),
        util.by_pixel(25.0, -89.5),
        util.by_pixel(27.0, -89.0),
        util.by_pixel(28.5, -88.5),
        util.by_pixel(30.5, -88.0),
        util.by_pixel(32.0, -87.0),
        util.by_pixel(33.5, -86.5),
        util.by_pixel(35.0, -85.5),
        util.by_pixel(36.5, -85.0),
        util.by_pixel(38.0, -84.0),
        util.by_pixel(39.5, -83.5),
        util.by_pixel(41.0, -82.5),
        util.by_pixel(42.5, -81.5),
        util.by_pixel(44.0, -80.5),
        util.by_pixel(45.0, -80.0),
        util.by_pixel(46.5, -79.0),
        util.by_pixel(47.5, -78.0),
        util.by_pixel(49.0, -77.0),
        util.by_pixel(50.0, -76.0),
        util.by_pixel(51.5, -75.0),
        util.by_pixel(52.5, -74.0),
        util.by_pixel(53.5, -73.0),
        util.by_pixel(54.5, -72.0),
        util.by_pixel(55.5, -71.0),
        util.by_pixel(56.5, -70.0),
        util.by_pixel(57.5, -68.5),
        util.by_pixel(58.5, -67.5),
        util.by_pixel(59.0, -66.5),
        util.by_pixel(60.0, -65.5),
        util.by_pixel(60.5, -64.0),
        util.by_pixel(61.5, -63.0),
        util.by_pixel(62.0, -62.0),
        util.by_pixel(62.5, -61.0),
        util.by_pixel(63.0, -59.5),
        util.by_pixel(63.5, -58.5),
        util.by_pixel(64.0, -57.5),
        util.by_pixel(64.5, -56.0),
        util.by_pixel(65.0, -55.0),
        util.by_pixel(65.5, -53.5),
        util.by_pixel(65.5, -52.5),
        util.by_pixel(66.0, -51.5),
        util.by_pixel(66.5, -50.0),
        util.by_pixel(66.5, -49.0),
        util.by_pixel(66.5, -48.0),
        util.by_pixel(66.5, -46.5),
        util.by_pixel(67.0, -45.5),
        util.by_pixel(67.0, -44.0),
        util.by_pixel(67.0, -43.0),
        util.by_pixel(66.5, -42.0),
        util.by_pixel(66.5, -40.5),
        util.by_pixel(66.5, -39.5),
        util.by_pixel(66.5, -38.5),
        util.by_pixel(66.5, -37.5),
        util.by_pixel(66.5, -36.0),
        util.by_pixel(67.0, -35.0),
        util.by_pixel(67.0, -34.0),
        util.by_pixel(67.0, -32.5),
        util.by_pixel(67.0, -31.5),
        util.by_pixel(67.0, -30.5),
        util.by_pixel(67.0, -29.0),
        util.by_pixel(67.0, -28.0),
        util.by_pixel(67.0, -26.5),
        util.by_pixel(66.5, -25.5),
        util.by_pixel(66.5, -24.5),
        util.by_pixel(66.0, -23.0),
        util.by_pixel(66.0, -22.0),
        util.by_pixel(65.5, -20.5),
        util.by_pixel(65.0, -19.5),
        util.by_pixel(65.0, -18.5),
        util.by_pixel(64.5, -17.0),
        util.by_pixel(64.0, -16.0),
        util.by_pixel(63.0, -15.0),
        util.by_pixel(62.5, -13.5),
        util.by_pixel(62.0, -12.5),
        util.by_pixel(61.5, -11.5),
        util.by_pixel(60.5, -10.0),
        util.by_pixel(60.0, -9.0),
        util.by_pixel(59.0, -8.0),
        util.by_pixel(58.0, -7.0),
        util.by_pixel(57.5, -6.0),
        util.by_pixel(56.5, -4.5),
        util.by_pixel(55.5, -3.5),
        util.by_pixel(54.5, -2.5),
        util.by_pixel(53.5, -1.5),
        util.by_pixel(52.0, -0.5),
        util.by_pixel(51.0, 0.0),
        util.by_pixel(50.0, 1.0),
        util.by_pixel(48.5, 2.0),
        util.by_pixel(47.5, 3.0),
        util.by_pixel(46.0, 4.0),
        util.by_pixel(45.0, 5.0),
        util.by_pixel(43.5, 5.5),
        util.by_pixel(42.0, 6.5),
        util.by_pixel(40.5, 7.5),
        util.by_pixel(39.0, 8.0),
        util.by_pixel(37.5, 9.0),
        util.by_pixel(36.0, 10.0),
        util.by_pixel(34.5, 10.5),
        util.by_pixel(33.0, 11.5),
        util.by_pixel(31.5, 12.0),
        util.by_pixel(29.5, 12.5),
        util.by_pixel(28.0, 13.5),
        util.by_pixel(26.5, 14.0),
        util.by_pixel(24.5, 14.5),
        util.by_pixel(23.0, 15.0),
        util.by_pixel(21.0, 15.5),
        util.by_pixel(19.0, 16.0),
        util.by_pixel(17.5, 16.5),
        util.by_pixel(15.5, 17.0),
        util.by_pixel(13.5, 17.5),
        util.by_pixel(11.5, 18.0),
        util.by_pixel(10.0, 18.0),
        util.by_pixel(8.0, 18.5),
        util.by_pixel(6.0, 19.0),
        util.by_pixel(4.0, 19.0)
      },
      cannon_barrel_recoil_shiftings = {
        {x = -0.000, y = 0.040, z = -0.000},
        {x = -0.789, y = 0.037, z = -0.351},
        {x = -1.578, y = 0.035, z = -0.702},
        {x = -2.367, y = 0.033, z = -1.054},
        {x = -3.155, y = 0.031, z = -1.405},
        {x = -3.944, y = 0.028, z = -1.756},
        {x = -3.931, y = 0.028, z = -1.750},
        {x = -3.901, y = 0.028, z = -1.737},
        {x = -3.854, y = 0.029, z = -1.716},
        {x = -3.790, y = 0.029, z = -1.688},
        {x = -3.711, y = 0.029, z = -1.652},
        {x = -3.617, y = 0.029, z = -1.610},
        {x = -3.508, y = 0.030, z = -1.562},
        {x = -3.385, y = 0.030, z = -1.507},
        {x = -3.249, y = 0.030, z = -1.447},
        {x = -3.102, y = 0.031, z = -1.381},
        {x = -2.944, y = 0.031, z = -1.311},
        {x = -2.776, y = 0.032, z = -1.236},
        {x = -2.599, y = 0.032, z = -1.157},
        {x = -2.416, y = 0.033, z = -1.076},
        {x = -2.226, y = 0.033, z = -0.991},
        {x = -2.032, y = 0.034, z = -0.905},
        {x = -1.835, y = 0.034, z = -0.817},
        {x = -1.635, y = 0.035, z = -0.728},
        {x = -1.436, y = 0.035, z = -0.639},
        {x = -1.238, y = 0.036, z = -0.551},
        {x = -1.042, y = 0.037, z = -0.464},
        {x = -0.851, y = 0.037, z = -0.379},
        {x = -0.665, y = 0.038, z = -0.296},
        {x = -0.485, y = 0.038, z = -0.216},
        {x = -0.314, y = 0.039, z = -0.140},
        {x = -0.152, y = 0.039, z = -0.068}
      },
      cannon_barrel_light_direction = {0.5976251, 0.0242053, -0.8014102},
      cannon_barrel_recoil_shiftings_load_correction_matrix = {
        {0, 0.25, 0},
        {-0.25, 0, 0},
        {0, 0, 0.25}
      },
      wheels = standard_train_wheels,
      rail_category = "regular",
      drive_over_tie_trigger = drive_over_tie(),
      tie_distance = 50,
      working_sound = {
        sound = {
          filename = "__base__/sound/train-wheels.ogg",
          volume = 0.6
        },
        match_volume_to_activity = true
      },
      crash_trigger = crash_trigger(),
      open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.85},
      close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.75},
      sound_minimum_speed = 0.5,
      vehicle_impact_sound = {filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65}
    }
  }
)
