return {
    ["grass-1"] = "vegetation-green-grass-1" ,
    ["grass-2"] = "vegetation-green-grass-2" ,
    ["grass-3"] = "vegetation-green-grass-3" ,
    ["grass-4"] = "vegetation-green-grass-4" ,
    ["dirt-1"] = "mineral-tan-dirt-1" ,
    ["dirt-2"] = "mineral-tan-dirt-2" ,
    ["dirt-3"] = "mineral-tan-dirt-1" ,
    ["dirt-4"] = "mineral-tan-dirt-2" ,
    ["dirt-5"] = "mineral-tan-dirt-3" ,
    ["dirt-6"] = "mineral-tan-dirt-5" ,
    ["dirt-7"] = "mineral-tan-dirt-4" ,
    ["dry-dirt"] = "mineral-tan-dirt-6" ,
    ["red-desert-0"] = "vegetation-olive-grass-2" ,
    ["red-desert-1"] = "mineral-brown-dirt-1" ,
    ["red-desert-2"] = "mineral-brown-dirt-5" ,
    ["red-desert-3"] = "mineral-brown-dirt-6" ,
    ["sand-1"] = "mineral-brown-sand-1" ,
    ["sand-2"] = "mineral-brown-sand-1" ,
    ["sand-3"] = "mineral-brown-sand-2" ,
    ["sand-4"] = "mineral-brown-sand-3" ,
}
