data:extend(
{
  {
    type = "double-setting",
    name = "customarathon-ingredients",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 0.1,
    maximum_value = 10,
    order = "aa",
  },
  {
    type = "bool-setting",
    name = "customarathon-circuits",
    setting_type = "startup",
    default_value = false,
    order = "ab",
  },
  {
    type = "double-setting",
    name = "customarathon-usables",
    setting_type = "startup",
    default_value = 2,
    minimum_value = 0.1,
    maximum_value = 20,
    order = "ba",
  },
  {
    type = "double-setting",
    name = "customarathon-tiers",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 0.5,
    maximum_value = 2,
    order = "bb",
  },
  {
    type = "bool-setting",
    name = "customarathon-successive",
    setting_type = "startup",
    default_value = false,
    order = "bc",
  },
  {
    type = "double-setting",
    name = "customarathon-crafting-time",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 0.1,
    maximum_value = 20,
    order = "ca",
  },
  {
    type = "bool-setting",
    name = "customarathon-modules",
    setting_type = "startup",
    default_value = false,
    order = "da",
  },
  {
    type = "bool-setting",
    name = "customarathon-ammos",
    setting_type = "startup",
    default_value = false,
    order = "db",
  },
  {
    type = "bool-setting",
    name = "customarathon-new-items",
    setting_type = "startup",
    default_value = false,
    order = "ea",
  },
})